# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594a7ad07c88359b488c6db35e2fc281f6c05108a03077d74089965b8ab9f5c03aa1b0df12a8bb5fac26c4366efd62a6a4e1946bbe6237fc65b2ebb04e578139

test:
  secret_key_base: 70e509581b18894c1aa3be02f4284aa8d9aa44a4c81574abf6112254030821dfb6bb2f2b3661eaa728ac521cabe8bb1f9e789c7ac8cd36460d99778ea41c9f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
